name: Build and Test

on: [push]

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup PyInvoke
        run: pip install invoke

      - name: Setup bin dir
        run: mkdir -p ~/bin

      - name: Install DASM
        uses: robinraju/release-downloader@v1.8
        with:
          repository: dasm-assembler/dasm
          tag: 2.20.14.1
          extract: true
          out-file-path: ~/bin

      - name: Install Gopher2600
        run: |
          ls -la ~/bin
          cd ~/bin
          curl -O https://github.com/JetSetIlly/Gopher2600/releases/download/v0.27.0/gopher2600_linux_amd64 --output
          chmod a+x ~/bin/gopher2600

      - name: Build Everything
        run: |
          export DASM_BIN=~/app/dasm
          export GOPHER_BIN=~/bin/gopher2600
          export DASMINC=~/app/machines/atari2600
          inv build
