name: Build and Test

on: [push]

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup PyInvoke
        run: pip install invoke

      - name: Install DASM
        uses: robinraju/release-downloader@v1.8
        with:
          repository: dasm-assembler/dasm
          tag: 2.20.14.1
          extract: true
          out-file-path: .bin

      - name: Install Gopher2600
        uses: robinraju/release-downloader@v1.8
        with:
          repository: JetSetIlly/Gopher2600
          tag: v0.27.0
          fileName: gopher2600_linux_amd64
          out-file-path: .bin

      - name: Build Everything
        run: |
          export DASM_BIN=.bin/dasm
          export GOPHER_BIN=.bin/gopher2600_linux_amd64
          export DASMINC=.bin/machines/atari2600
          inv build
