name: Build and Test

on: [push]

env:
  DASM_BIN: /tmp/bin/dasm
  GOPHER_BIN: /tmp/bin/gopher2600_linux_amd64
  DASMINC: /tmp/bin/machines/atari2600

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup PyInvoke
        run: pip install invoke

      - name: Install DASM
        uses: robinraju/release-downloader@v1.8
        with:
          repository: dasm-assembler/dasm
          tag: 2.20.14.1
          extract: true
          fileName: dasm-2.20.14.1-linux-x64.tar.gz
          out-file-path: /tmp/bin

      - name: Install Gopher2600
        uses: robinraju/release-downloader@v1.8
        with:
          repository: JetSetIlly/Gopher2600
          tag: v0.27.0
          fileName: gopher2600_linux_amd64
          out-file-path: /tmp/bin

      - name: Exec perm on Gopher2600
        run: chmod a+x $GOPHER_BIN

      - name: Build Everything
        run: inv build

      - name: Test Everything
        run: inv test
